# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37df131c1b26efe2b37998256903e83d0bfe45c5be0bfddcd716e69b2cc300f53f75337c76ce5e9eaf371f81f48568011bdd90eb4772ad022d49eabd4b809935

test:
  secret_key_base: 3f4adaace44c52ece54b6d364a75db0de727b4f316ec0f6a1813934d0894922419e22ac322b8d7a32e6789dcbc99ce429edadcea06aae8d5487c6852e16d85d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
